// rtl/ntt_top_wrapper.sv — Structural top-level wrapper
//
// Pure structural: instantiates HLS IP (ntt_top), three dual-port BRAMs
// (BRAM_A, BRAM_B, BRAM_C), and bram_mux. No always blocks, no logic.
//
// Generated by: vivado/ntt_bd.tcl (Vivado block design export)
// Manually maintained for simulation purposes.
