// hls/ntt_top.cpp — Top-level HLS function
//
// Sequences the full negacyclic polynomial multiplication pipeline:
//   NTT(a) -> NTT(b) -> mul_ntt(a, b, c) -> INTT(c)
//
// Interface: m_axi for bulk data (a, b, c live in PS DDR, accessed via HP0).
// HLS bursts all N coefficients in at startup, computes on internal storage,
// bursts results back. Physical addresses of a, b, c are passed as AXI-Lite
// offset registers (auto-generated by offset=slave).
//
// PS driver must:
//   1. Flush dcache for a/b buffers before asserting ap_start
//   2. Invalidate dcache for c buffer after ap_done before reading results
// Skipping either causes silent wrong answers — the HP port bypasses the cache.

#include "ntt_top.h"
#include "ntt_engine.h"
#include "mul_ntt.h"

void ntt_top(coef_t a[N], coef_t b[N], coef_t c[N]) {
#pragma HLS INTERFACE ap_ctrl_hs port=return
#pragma HLS INTERFACE ap_memory port=a storage_type=ram_1p
#pragma HLS INTERFACE ap_memory port=b storage_type=ram_1p
#pragma HLS INTERFACE ap_memory port=c storage_type=ram_1p

    ntt_engine(a, false);
    ntt_engine(b, false);
    mul_ntt(a, b, c);
    ntt_engine(c, true);
}
