// hls/ntt_top.h — Top-level HLS function declarations
#ifndef NTT_TOP_H
#define NTT_TOP_H

#include "ntt_engine.h"

// Top-level: full negacyclic polynomial multiplication pipeline.
// AXI-Lite control registers are auto-generated by HLS from the
// #pragma HLS INTERFACE s_axilite directives in ntt_top.cpp.
//
// Register map (generated by HLS synthesis, base address from block design):
//   0x00  CTRL   [0] AP_START — write 1 to begin computation
//                [1] AP_DONE  — reads 1 when complete
//                [2] AP_IDLE  — reads 1 when idle/waiting
void ntt_top(coef_t a[N], coef_t b[N], coef_t c[N]);

#endif // NTT_TOP_H
