// hls/ntt_top.cpp — Top-level HLS function
//
// Sequences the full negacyclic polynomial multiplication pipeline:
//   pre_twist(a) -> NTT(a) -> pre_twist(b) -> NTT(b)
//   -> mul_ntt(a,b,c) -> INTT(c) -> post_twist(c)
//
// AXI-Lite control registers are auto-generated by:
//   #pragma HLS INTERFACE s_axilite port=return bundle=CTRL
// Do NOT hand-write AXI-Lite logic elsewhere.

#include "ntt_top.h"
#include "barrett.h"
#include "twist.h"
#include "mul_ntt.h"

void ntt_top(coef_t a[N], coef_t b[N], coef_t c[N]) {
#pragma HLS INTERFACE s_axilite port=return bundle=CTRL
#pragma HLS INTERFACE bram port=a
#pragma HLS INTERFACE bram port=b
#pragma HLS INTERFACE bram port=c

    // TODO: implement pipeline using twist(), ntt_engine(), mul_ntt()
    (void)a; (void)b; (void)c;
}
