// hls/tb_ntt_hls.cpp — HLS C-sim testbench
//
// Reads test vectors generated by golden/test_ntt.py.
// Verifies NTT engine output against expected values.

#include "ntt_engine.h"
#include <cstdio>

int main() {
    // TODO: load test vectors, run NTT, compare
    return 0;
}
