#!/usr/bin/env python3
"""
scripts/gen_twiddle_rom.py — Twiddle factor table generator

Generates:
  hls/twiddle_rom.h        — C++ constexpr arrays for HLS compile-time use
  vivado/twiddle_omega.coe — Vivado BRAM init file for omega table
  vivado/twiddle_psi.coe   — Vivado BRAM init file for psi table

Usage:
    python gen_twiddle_rom.py --n 4 --q 17     # dev params
    python gen_twiddle_rom.py --n 256 --q 3329  # full Kyber

Output values must match golden/ntt.py:NTTConfig.from_params(n, q) exactly.
"""

import argparse
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'golden'))
from ntt import NTTConfig


def gen_twiddle_rom(n: int, q: int, repo_root: str = '..') -> None:
    cfg = NTTConfig.from_params(d=n, q=q)

    coef_w = q.bit_length()
    hls_dir    = os.path.join(repo_root, 'hls', 'src')
    vivado_dir = os.path.join(repo_root, 'vivado')
    os.makedirs(hls_dir, exist_ok=True)
    os.makedirs(vivado_dir, exist_ok=True)

    # --- C++ header for HLS ---
    def arr(name: str, values: list) -> str:
        vals = ', '.join(str(v) for v in values)
        return f'constexpr coef_t {name}[N] = {{{vals}}};'

    header_path = os.path.join(hls_dir, 'twiddle_rom.h')
    with open(header_path, 'w') as f:
        f.write(f'// hls/src/twiddle_rom.h — Generated by scripts/gen_twiddle_rom.py\n')
        f.write(f'// Parameters: n={n}, q={q}\n')
        f.write(f'// DO NOT EDIT — regenerate with: python scripts/gen_twiddle_rom.py --n {n} --q {q}\n')
        f.write(f'#ifndef TWIDDLE_ROM_H\n#define TWIDDLE_ROM_H\n\n')
        f.write(f'#include "ntt_engine.h"\n\n')
        f.write(arr('OMEGA_TABLE',     cfg.omega_powers)     + '\n')
        f.write(arr('INV_OMEGA_TABLE', cfg.inv_omega_powers) + '\n')
        f.write(arr('PSI_TABLE',       cfg.psi_powers)       + '\n')
        f.write(arr('INV_PSI_TABLE',   cfg.inv_psi_powers)   + '\n')
        f.write(f'constexpr coef_t INV_N = {cfg.inv_d};\n\n')
        f.write(f'#endif // TWIDDLE_ROM_H\n')
    print(f'Wrote {header_path}')

    # --- Vivado .coe BRAM init files ---
    def coe(values: list) -> str:
        lines = ['memory_initialization_radix=10;', 'memory_initialization_vector=']
        lines += [f'{v},' for v in values[:-1]]
        lines += [f'{values[-1]};']
        return '\n'.join(lines)

    for name, values in [
        ('twiddle_omega', cfg.omega_powers),
        ('twiddle_psi',   cfg.psi_powers),
    ]:
        coe_path = os.path.join(vivado_dir, f'{name}.coe')
        with open(coe_path, 'w') as f:
            f.write(coe(values))
        print(f'Wrote {coe_path}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate twiddle factor tables')
    parser.add_argument('--n', type=int, default=4,  help='Polynomial degree (default: 4)')
    parser.add_argument('--q', type=int, default=17, help='Modulus (default: 17)')
    parser.add_argument('--root', type=str, default=os.path.join(os.path.dirname(__file__), '..'),
                        help='Repository root (default: parent of scripts/)')
    args = parser.parse_args()

    gen_twiddle_rom(args.n, args.q, repo_root=args.root)
    print('Done.')
