#!/usr/bin/env python3
"""
scripts/gen_twiddle_rom.py — Single retargeting command for any (N, Q) parameter set.

Generates / updates:
  hls/src/ntt_engine.h     — #define parameters (NTT_N, NTT_Q, NTT_COEF_W, NTT_LOG2_N)
  hls/src/twiddle_rom.h    — twiddle tables for HLS
  vivado/twiddle_omega.coe — Vivado BRAM init file (omega table)
  vivado/twiddle_psi.coe   — Vivado BRAM init file (psi table)

Usage:
    python scripts/gen_twiddle_rom.py --n 4   --q 17    # dev params
    python scripts/gen_twiddle_rom.py --n 128 --q 3329  # full Kyber

After running, re-run HLS synthesis. Nothing else needs to change.

Requirements:
    q must be prime and 2n must divide (q - 1).
"""

import argparse
import math
import sys
import os
import re

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'golden'))
from ntt import NTTConfig


# Validation

def validate_params(n: int, q: int) -> None:
    """Abort with a clear message if (n, q) cannot support a negacyclic NTT."""
    from sympy import isprime
    if not isprime(q):
        sys.exit(f"Error: q={q} is not prime.")
    if n & (n - 1) != 0:
        sys.exit(f"Error: n={n} is not a power of two.")
    log2_n = int(math.log2(n))
    if 2 ** log2_n != n:
        sys.exit(f"Error: n={n} is not an exact power of two.")
    if (q - 1) % (2 * n) != 0:
        sys.exit(f"Error: 2n={2*n} does not divide q-1={q-1}. "
                 f"No primitive 2n-th root of unity exists mod q.")


# ntt_engine.h

def update_ntt_engine_h(n: int, q: int, hls_dir: str) -> None:
    """Rewrite the four #define lines in ntt_engine.h for the given (n, q)."""
    coef_w = q.bit_length()          # ceil(log2(q)) — minimum bits to hold a coefficient
    log2_n = int(math.log2(n))

    path = os.path.join(hls_dir, 'ntt_engine.h')
    with open(path, 'r') as f:
        src = f.read()

    replacements = {
        'NTT_N':      str(n),
        'NTT_Q':      str(q),
        'NTT_COEF_W': str(coef_w),
        'NTT_LOG2_N': str(log2_n),
    }
    for macro, value in replacements.items():
        # Match: #define MACRO <number>  (preserving surrounding whitespace and comment)
        src = re.sub(
            rf'(#define\s+{macro}\s+)\d+',
            lambda m, v=value: m.group(1) + v,
            src
        )

    with open(path, 'w') as f:
        f.write(src)
    print(f'Updated  {path}  (N={n}, Q={q}, COEF_W={coef_w}, LOG2_N={log2_n})')


# twiddle_rom.h

def gen_twiddle_rom_h(cfg: NTTConfig, n: int, q: int, hls_dir: str) -> None:
    def arr(name: str, values: list) -> str:
        vals = ', '.join(str(v) for v in values)
        return f'const coef_t {name}[N] = {{{vals}}};'

    path = os.path.join(hls_dir, 'twiddle_rom.h')
    with open(path, 'w') as f:
        f.write(f'// hls/src/twiddle_rom.h — Generated by scripts/gen_twiddle_rom.py\n')
        f.write(f'// Parameters: n={n}, q={q}\n')
        f.write(f'// DO NOT EDIT — regenerate with: python scripts/gen_twiddle_rom.py --n {n} --q {q}\n')
        f.write(f'#ifndef TWIDDLE_ROM_H\n#define TWIDDLE_ROM_H\n\n')
        f.write(f'#include "ntt_engine.h"\n\n')
        f.write(arr('OMEGA_TABLE',     cfg.omega_powers)     + '\n')
        f.write(arr('INV_OMEGA_TABLE', cfg.inv_omega_powers) + '\n')
        f.write(arr('PSI_TABLE',       cfg.psi_powers)       + '\n')
        f.write(arr('INV_PSI_TABLE',   cfg.inv_psi_powers)   + '\n')
        f.write(f'const coef_t INV_N = {cfg.inv_d};\n\n')
        f.write(f'#endif // TWIDDLE_ROM_H\n')
    print(f'Wrote    {path}')


# Vivado .coe files

def gen_coe_files(cfg: NTTConfig, vivado_dir: str) -> None:
    def coe(values: list) -> str:
        lines = ['memory_initialization_radix=10;', 'memory_initialization_vector=']
        lines += [f'{v},' for v in values[:-1]]
        lines += [f'{values[-1]};']
        return '\n'.join(lines)

    os.makedirs(vivado_dir, exist_ok=True)
    for name, values in [('twiddle_omega', cfg.omega_powers), ('twiddle_psi', cfg.psi_powers)]:
        path = os.path.join(vivado_dir, f'{name}.coe')
        with open(path, 'w') as f:
            f.write(coe(values))
        print(f'Wrote    {path}')


# Entry point

def check_params(n: int, q: int) -> None:
    """Verify structural math properties of (n, q). Does not write files."""
    cfg = NTTConfig.from_params(d=n, q=q)

    assert pow(cfg.omega, n, q) == 1,      "omega is not an n-th root of unity"
    assert pow(cfg.omega, n//2, q) == q-1, "omega^(n/2) != -1 mod q"
    assert pow(cfg.psi,   2*n, q) == 1,    "psi is not a 2n-th root of unity"
    assert pow(cfg.psi,   n,   q) == q-1,  "psi^n != -1 mod q"
    assert cfg.psi ** 2 % q == cfg.omega,  "psi^2 != omega"
    print(f"  structural checks: PASS  (omega^n=1, omega^(n/2)=-1, psi^(2n)=1, psi^2=omega)")
    print(f"  omega={cfg.omega}, psi={cfg.psi}, inv_n={cfg.inv_d}")
    print(f"  2n={2*n} | (q-1)={q-1}  =>  (q-1)/(2n) = {(q-1)//(2*n)}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Retarget the NTT accelerator to a new (N, Q) parameter set.'
    )
    parser.add_argument('--n',          type=int, default=4,   help='Polynomial degree (default: 4)')
    parser.add_argument('--q',          type=int, default=17,  help='Modulus (default: 17)')
    parser.add_argument('--check-only', action='store_true',
                        help='Validate params and check structural math; do not write any files')
    parser.add_argument('--root',       type=str,
                        default=os.path.join(os.path.dirname(__file__), '..'),
                        help='Repository root (default: parent of scripts/)')
    args = parser.parse_args()

    validate_params(args.n, args.q)

    if args.check_only:
        print(f'Checking (n={args.n}, q={args.q}) — no files will be written\n')
        check_params(args.n, args.q)
        print('\nAll checks passed.')
        sys.exit(0)

    cfg        = NTTConfig.from_params(d=args.n, q=args.q)
    hls_dir    = os.path.join(args.root, 'hls', 'src')
    vivado_dir = os.path.join(args.root, 'vivado')

    update_ntt_engine_h(args.n, args.q, hls_dir)
    gen_twiddle_rom_h(cfg, args.n, args.q, hls_dir)
    gen_coe_files(cfg, vivado_dir)

    print('\nDone. Re-run HLS synthesis to pick up the new parameters.')
